### PR TITLE
Update to support rpi / 2 / 3

### PR DESCRIPTION
**Pull request by mobileoverlord**
Sorry for the huge chunk but i just kinda couldn't stop. :)

**Changes in this PR**
- Updated the Makefile to support cross compiling and include ei.h
- Added helper functions utils / erlcmd
- Added upstream rpi_ws281x as a submodule
- Renamed the module out of the IO namespace
- Modifications to the API

The last one there I am not 100% sold on yet. I would like to take another pass at it, probably just break out the functions to support helpers for single channel support.

### CODE REVIEW

**Comment by GregMefford** [comment]
Really awesome, thank you! :rocket: :guitar: 

I really like the idea of pulling in the upstream project as a submodule - I thought about doing that but didn't get around to trying it and making sure it works with the build system.

I don't have a problem with the namespace change, but do you know how to best handle that with the hex package? Is there a way to have the old one forward to the new one, or will it just be a separate package with an incidentally-higher version number?

I'll hopefully get some time shortly to try it out and push an updated package to Hex.

**Comment by mobileoverlord** [comment]
There will be a inactive redirect feature to hex soon. I think we should just publish it again and worry about that later.

**Comment by kangguru** [comment]
oh my :) i was trying to get neopixel running on my rpi 2 and 3 and was always wondering why it works on the 1 just fine.... then i found this PR. 

although i'm completely new to elixir and nerves, could you give me a hint how it get this PR running? i've changed the debs.mix to point to this code, but due to the change that `rpi_ws281x` now is a submodule it cannot compile properly.

**Comment by mobileoverlord** [comment]
In your dependency add the option `submodules: true` and it will load them. Just call `deps.get` again

**Comment by GregMefford** [comment]
Lars: Good timing, huh? ;) I'm hoping to get this merged and published as
an updated hex package soon. I'm still working through a few issues with it
myself.

**Comment by mobileoverlord** [comment]
@GregMefford What kind of issues are you experiencing? I can update the PR to include those changes. Make a list and I'll blast through them.

**Comment by GregMefford** [comment]
@mobileoverlord I was able to build firmware for both `rpi` and `rpi2`, but in both cases, I don't actually get to an interactive IEx prompt using the HDMI screen, and the screen goes black shortly after it finishes booting (as if maybe something is crashing in the kernel).

I'm testing using the `neopixel` example from your PR to https://github.com/nerves-project/nerves-examples, but with the `nerves_neopixel` dep pointing to my local copy instead of your GitHub fork.

**Comment by kangguru** [comment]
yeah! awesome timing! so thanks for the submodule hint. this works great.

like @GregMefford i'm a little struggling in getting this to work, seems like `#setup` is not gone, right? i replaced it with `#start_link` which then led me to the iex. altough trying to render leaves me in a similar state and the display is turned of so fast ;) hard to grasp whats going on there, but it crashed :) obviously.

**Pull request merged**
