### PR TITLE
Update rpi_ws281x with rpi3 B+ support

### PR DESCRIPTION
**Pull request by acrogenesis**
Updates the submodule rpi_ws281x for rpi3B+ support

### CODE REVIEW

**Comment by acrogenesis** [comment]
Hello @GregMefford is it missing something to get merged?

**Comment by GregMefford** [comment]
Wow, sorry this sat for so long, @acrogenesis! I've recently switched jobs, which involved some travel and administrative work, so I missed this notification.

Thanks for taking the time to get this updated. I'll work on getting it merged and released soon.
I'm hoping to also release an updated version of the library soon, which adds a lot of nice features for driving NeoPixel matrix displays and other arbitrary configurations of NeoPixel strips. I mostly just need to update some of the documentation.

**Comment by acrogenesis** [comment]
Hello @GregMefford think we could get this merged :)

**Comment by GregMefford** [comment]
Yikes sorry. I keep trying to find time to polish off the rest of the stuff
I’m working on for a big 1.0 rewrite, but it’s obviously taking forever.
I’ll get this merged and tested and make a last release before the big
change.

**Comment by GregMefford** [comment]
I don't actually own an RPi3 B+ yet, but I was able to get this tested on my RPi0, so I'm going to go ahead and merge/release and you can let me know if it's working for you on the 3B+. 🚀

**Pull request merged**
